name: Health check

# on:
#   schedule:
#     - cron:  '55 * * * *'
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  service_health_check:
    runs-on: ubuntu-18.04
    steps:
      - id: healthcheck
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://immense-garden-66508.herokuapp.com/
          max-attempts: 1